# Generated by Django 4.0.4 on 2022-10-15 23:30

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=home.models.file_model_path)),
                ('element_id', models.CharField(default='-1', max_length=100)),
                ('element_type', models.CharField(choices=[('Acta de Campo', 'Acta de Campo'), ('Acta de Conformidad', 'Acta de Conformidad'), ('Otros', 'Otros')], default='Otros', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proporcion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Valor_Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vindicador_indicador', to='home.indicadores')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semana', models.IntegerField()),
                ('Acta_de_Campo', models.ManyToManyField(blank=True, related_name='actC_doc', to='home.documento')),
                ('Acta_de_Inconformidad', models.ManyToManyField(blank=True, related_name='actI_doc', to='home.documento')),
                ('Otros', models.ManyToManyField(blank=True, related_name='otros_doc', to='home.documento')),
                ('indicadores', models.ManyToManyField(blank=True, related_name='semana_indicador', to='home.valor_indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('supervisor', models.CharField(max_length=100)),
                ('contratista_fiscal', models.CharField(max_length=100)),
                ('num_contrato', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(null=True, upload_to=home.models.image_upload)),
                ('semanas', models.ManyToManyField(blank=True, related_name='obra_week', to='home.semana')),
            ],
        ),
    ]
