# Generated by Django 4.0.4 on 2022-10-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_documento_indicadores_valor_indicador_semana_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='num_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
