# Generated by Django 4.0.4 on 2022-11-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_semana_num_semana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadores',
            old_name='proporcion',
            new_name='ponderacion',
        ),
    ]
