# Generated by Django 4.0.4 on 2022-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_proporcion_indicadores_ponderacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='cumplimiento_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
