# Generated by Django 4.0.4 on 2022-11-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_semana_cumplimiento_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semana',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
