# Generated by Django 4.0.4 on 2022-11-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_semana_año_semana_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semana',
            options={'ordering': ['año', 'num_semana']},
        ),
        migrations.AlterField(
            model_name='valor_indicador',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
