# Generated by Django 4.0.4 on 2022-12-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_semana_options_alter_valor_indicador_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='element_id',
        ),
    ]
