# Generated by Django 4.0.4 on 2022-12-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_element_type_documento_tipo_de_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='week_doc', to='home.documento'),
        ),
    ]
