# Generated by Django 4.0.4 on 2022-12-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_semana_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='semana',
        ),
    ]
